name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: 🛠️ Create spell checker config file
      run: |
        touch _typos.toml
        echo "[files]" >> _typos.toml
        echo "extend-exclude = ['typos/**', 'public/**']" >> _typos.toml
      shell: bash
    
    - name: 📂 Typo scan output folder
      run: mkdir typos-report & touch typos-report/typos.txt & touch typos-report/typos.diff
      shell: bash

    - name: 🚫 Preform typo scan
      run: |
        ./typos >> typos-report/typos.txt || true
        ./typos >> typos-report/typos.diff --diff || true
      shell: bash
    
    - uses: actions/upload-artifact@v3
      with:
        name: typos-report
        path: typos-report