name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash

    - name:  ðŸ› ï¸ Configure rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
    
    - uses: Swatinem/rust-cache@v2
      with:
        prefix-key: ""
        shared-key: ""
        key: ""
        env-vars: ""
        workspaces: ""
        cache-directories: ""
        cache-targets: ""
        cache-on-failure: ""
        save-if: ""

    - name: ðŸ› ï¸ Configure rust cargo (package manager)
      uses: actions-rs/cargo@v1
  
    - name: ðŸ“¦ Install spell-checker dependency
      run: cargo install typos-cli
      shell: bash
      
    - name: ðŸ› ï¸ Create spell checker config file
      run: |
        touch _typos.toml
        echo "[files]" >> _typos.toml
        echo "extend-exclude = ['typos/**', 'public/**']" >> _typos.toml
      shell: bash

    - name: ðŸš« Preform typo scan
      id: typo-scan
      run: |
        mkdir typos
        touch typos/typos.txt
        touch typos/README.md
        echo '## Detected Typos' >> typos/typos.txt
        ${{ github.workspace }}/../../../.cargo/bin/typos >> typos/typos.txt || true
        echo '## Detected Typos Diff' >> typos/README.md
        echo '```diff' >> typos/README.md
        ${{ github.workspace }}/../../../.cargo/bin/typos --diff >> typos/README.md || true
      shell: bash