name: Test Action
on: push

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run this action to test it
        uses: ./
        with:
          scan-exclude-match: '[''typos/**'', ''public/**'']'